import Head from "next/head";
import { useQuery } from "@tanstack/react-query";
import { getAllCurrencies, getConvertRate, getHistoricalData, getLatest } from "@/src/api";

export default function Home() {
  // const { data, error } = useQuery({ queryKey: ["todos"], queryFn: getLatest });
  // // console.log("ce: ", { data, error});

  // const { data, error } = useQuery({ queryKey: ["todos"], queryFn:()=> getConvertRate('USD', 'BDT', 12) });
  // console.log("ce: ", data, error);

  return (
    <>
      <Head>
        <title>Currency Exchanger</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="text-3xl">hello there</main>
    </>
  );
}
