export const DEFAULT_API_SUFFIX = `?app_id=${process.env.NEXT_PUBLIC_API_APP_ID}`;

export enum APP_DEFAULTS {
  CURRENCY_BASE = "USD",
  CURRENCY_TO_TARGET = "BDT",
  CONVERT_VALUE = 1,
  INTERVAL = 10000,
  HISTORY_IN_DAYS = 90,
}
